-- V11: Testimonios y FAQs para landing pages
-- Fecha: 2026-02-05

-- Tabla de testimonios
CREATE TABLE IF NOT EXISTS TESTIMONIALS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    AUTHOR_NAME VARCHAR(100) NOT NULL,
    TEXT TEXT NOT NULL,
    RATING INT NOT NULL DEFAULT 5,
    DISPLAY_ORDER INT DEFAULT 0,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_testimonials_user FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX idx_testimonials_user ON TESTIMONIALS(USER_ID, ACTIVE, DISPLAY_ORDER);

-- Tabla de FAQs
CREATE TABLE IF NOT EXISTS FAQS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    QUESTION VARCHAR(500) NOT NULL,
    ANSWER TEXT NOT NULL,
    DISPLAY_ORDER INT DEFAULT 0,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_faqs_user FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX idx_faqs_user ON FAQS(USER_ID, ACTIVE, DISPLAY_ORDER);
