-- =============================================
-- V5: Landing page / Portfolio fields
-- =============================================

-- New profile fields for public landing page
ALTER TABLE BUSINESS_CONFIG ADD COLUMN BUSINESS_DESCRIPTION TEXT;
ALTER TABLE BUSINESS_CONFIG ADD COLUMN ADDRESS VARCHAR(255);
ALTER TABLE BUSINESS_CONFIG ADD COLUMN CITY VARCHAR(100);
ALTER TABLE BUSINESS_CONFIG ADD COLUMN PROVINCE VARCHAR(100);
ALTER TABLE BUSINESS_CONFIG ADD COLUMN INSTAGRAM_URL VARCHAR(255);
ALTER TABLE BUSINESS_CONFIG ADD COLUMN FACEBOOK_URL VARCHAR(255);
ALTER TABLE BUSINESS_CONFIG ADD COLUMN WHATSAPP_NUMBER VARCHAR(20);
ALTER TABLE BUSINESS_CONFIG ADD COLUMN WEBSITE_URL VARCHAR(255);
ALTER TABLE BUSINESS_CONFIG ADD COLUMN GOOGLE_MAPS_EMBED_URL VARCHAR(1000);

-- Portfolio images table
CREATE TABLE PORTFOLIO_IMAGES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BUSINESS_CONFIG_ID BIGINT NOT NULL,
    IMAGE_URL VARCHAR(1000) NOT NULL,
    CAPTION VARCHAR(255),
    DISPLAY_ORDER INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_PORTFOLIO_BUSINESS FOREIGN KEY (BUSINESS_CONFIG_ID) REFERENCES BUSINESS_CONFIG(ID)
);

CREATE INDEX IDX_PORTFOLIO_BUSINESS ON PORTFOLIO_IMAGES(BUSINESS_CONFIG_ID);
