-- Fase 3: Dominios personalizados

CREATE TABLE CUSTOM_DOMAINS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    DOMAIN VARCHAR(255) NOT NULL UNIQUE,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    VERIFICATION_TOKEN VARCHAR(64),
    SSL_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    SSL_CERTIFICATE_EXPIRES DATETIME NULL,
    LAST_VERIFICATION_ATTEMPT DATETIME NULL,
    VERIFICATION_ERROR VARCHAR(500),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VERIFIED_AT DATETIME NULL,

    CONSTRAINT FK_custom_domain_user FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    INDEX idx_custom_domain_domain (DOMAIN),
    INDEX idx_custom_domain_status (STATUS),
    INDEX idx_custom_domain_user (USER_ID)
);
